### ISSUE TITLE
Error when leeching 

### ISSUE THREAD

**Issue by BilliBoleMeow** [Sam-Max/Rclone-Tg-Bot#12]
2022-06-28T07:03:34.093876+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-28T07:03:34.093876+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-06-28T07:03:34.093877+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-06-28T07:03:34.093877+00:00 app[worker.1]:   File "/usr/src/app/bot/core/menus/callbacks/handle_leech_menu_cb.py", line 65, in handle_setting_leech_menu_callback
2022-06-28T07:03:34.093878+00:00 app[worker.1]:     await rclone_leech.leech()
2022-06-28T07:03:34.093878+00:00 app[worker.1]:   File "/usr/src/app/bot/uploaders/rclone/rclone_leech.py", line 71, in leech
2022-06-28T07:03:34.093879+00:00 app[worker.1]:     rcres= await self.__rclone_update()
2022-06-28T07:03:34.093879+00:00 app[worker.1]:   File "/usr/src/app/bot/uploaders/rclone/rclone_leech.py", line 174, in __rclone_update
2022-06-28T07:03:34.093880+00:00 app[worker.1]:     if time.time() - start > edit_time:
2022-06-28T07:03:34.093880+00:00 app[worker.1]: TypeError: '>' not supported between instances of 'float' and 'NoneType'

This happens after we send leech command and select file/folder to be leeched. Nothing gets uploaded and bot shows this error.

Also i do hope you are alright and recovering after surgery greatly as i saw previous issue comment.

**Comment by Sam-Max** [comment]
> 

Thanks so much, I am getting better. I tested leeching a file and a folder and is working fine for me. Make sure you have a value on EDIT_SLEEP_SECS on config.env. Also if you are running bot on vps try delete container and image, and redeploy again.

**Comment by BilliBoleMeow** [comment]
Thank You
