### ISSUE TITLE
Qbit Error

### ISSUE THREAD

**Issue by thomassch8861** [Sam-Max/Rclone-Tg-Bot#21]
When try to use qb commands on a torrent I get this error.
022-08-05 13:39:11,209 ERROR MainThread pyrogram.dispatcher 'builtin_function_or_method' object has no attribute 'time'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/core/handlers/handle_mirror_cm.py", line 29, in handle_qbit_mirror_command
    await mirror(client, message, isQbit=True)
  File "/usr/src/app/bot/core/handlers/handle_mirror_cm.py", line 114, in mirror
    state, message, path, name = await qbit_dl.add_qb_torrent(link)
  File "/usr/src/app/bot/downloaders/qbit/qbit_downloader.py", line 39, in add_qb_torrent
    time_s= str(time.time()).replace(".","")
AttributeError: 'builtin_function_or_method' object has no attribute 'time'

**Comment by Sam-Max** [comment]
Yes I know the issue, I will fix soon
