### ISSUE TITLE
qbittorrent download not responding

### ISSUE THREAD

**Issue by b1fly** [Sam-Max/Rclone-Tg-Bot#22]
nothing happens

`2022-08-06 12:17:13,058 INFO MainThread bot Rclone file loaded!!
2022-08-06 12:17:13,582 INFO MainThread bot Initializing Aria2c
2022-08-06 12:17:39,076 INFO MainThread bot MEGA_API_KEY not provided!
2022-08-06 12:17:40,613 INFO MainThread telethon.network.mtprotosender Connecting to 149.154.167.51:443/TcpFull...
2022-08-06 12:17:42,482 INFO MainThread telethon.network.mtprotosender Connection to 149.154.167.51:443/TcpFull complete!
2022-08-06 12:17:43,848 INFO MainThread telethon.client.users Phone migrated to 5
2022-08-06 12:17:43,848 INFO MainThread telethon.client.telegrambaseclient Reconnecting to new data center 5
2022-08-06 12:17:44,101 INFO MainThread telethon.network.mtprotosender Disconnecting from 149.154.167.51:443/TcpFull...
2022-08-06 12:17:44,101 INFO MainThread telethon.network.mtprotosender Disconnection from 149.154.167.51:443/TcpFull complete!
2022-08-06 12:17:44,101 INFO MainThread telethon.network.mtprotosender Connecting to 91.108.56.128:443/TcpFull...
2022-08-06 12:17:45,287 INFO MainThread telethon.network.mtprotosender Connection to 91.108.56.128:443/TcpFull complete!
2022-08-06 12:17:45,562 INFO MainThread bot Telethon client created.
2022-08-06 12:17:46,041 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC2
2022-08-06 12:17:46,041 INFO MainThread pyrogram.connection.connection Connecting...
2022-08-06 12:17:46,288 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO
2022-08-06 12:17:48,049 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk
2022-08-06 12:17:48,049 INFO MainThread pyrogram.connection.connection Disconnected
2022-08-06 12:17:48,223 INFO MainThread pyrogram.connection.connection Connecting...
2022-08-06 12:17:48,459 INFO MainThread pyrogram.connection.connection Connected! Production DC2 - IPv4 - TCPAbridgedO
2022-08-06 12:17:48,459 INFO MainThread pyrogram.session.session NetworkTask started
2022-08-06 12:17:48,973 INFO MainThread pyrogram.session.internals.msg_id Time synced: 2022-08-06 12:17:48.858429 UTC
2022-08-06 12:17:49,531 INFO MainThread pyrogram.session.session Session initialized: Layer 143
2022-08-06 12:17:49,532 INFO MainThread pyrogram.session.session Device: CPython 3.10.4 - Pyrogram 2.0.35
2022-08-06 12:17:49,532 INFO MainThread pyrogram.session.session System: Linux 5.4.0-1078-oracle (EN)
2022-08-06 12:17:49,532 INFO MainThread pyrogram.session.session Session started
2022-08-06 12:17:49,560 INFO MainThread pyrogram.session.session PingTask started
2022-08-06 12:17:49,871 INFO MainThread pyrogram.session.session PingTask stopped
2022-08-06 12:17:49,872 INFO MainThread pyrogram.connection.connection Disconnected
2022-08-06 12:17:49,872 INFO MainThread pyrogram.session.session NetworkTask stopped
2022-08-06 12:17:49,872 INFO MainThread pyrogram.session.session Session stopped
2022-08-06 12:17:49,962 INFO MainThread pyrogram.session.auth Start creating a new auth key on DC5
2022-08-06 12:17:49,962 INFO MainThread pyrogram.connection.connection Connecting...
2022-08-06 12:17:50,041 INFO MainThread pyrogram.connection.connection Connected! Production DC5 - IPv4 - TCPAbridgedO
2022-08-06 12:17:51,269 INFO MainThread pyrogram.session.auth Done auth key exchange: DhGenOk
2022-08-06 12:17:51,269 INFO MainThread pyrogram.connection.connection Disconnected
2022-08-06 12:17:51,388 INFO MainThread pyrogram.connection.connection Connecting...
2022-08-06 12:17:51,466 INFO MainThread pyrogram.connection.connection Connected! Production DC5 - IPv4 - TCPAbridgedO
2022-08-06 12:17:51,466 INFO MainThread pyrogram.session.session NetworkTask started
2022-08-06 12:17:51,869 INFO MainThread pyrogram.session.session Session initialized: Layer 143
2022-08-06 12:17:51,869 INFO MainThread pyrogram.session.session Device: CPython 3.10.4 - Pyrogram 2.0.35
2022-08-06 12:17:51,869 INFO MainThread pyrogram.session.session System: Linux 5.4.0-1078-oracle (EN)
2022-08-06 12:17:51,869 INFO MainThread pyrogram.session.session Session started
2022-08-06 12:17:51,870 INFO MainThread pyrogram.session.session PingTask started
2022-08-06 12:17:52,340 INFO MainThread pyrogram.dispatcher Started 8 HandlerTasks
2022-08-06 12:17:52,340 INFO MainThread bot pyro Bot client created
2022-08-06 12:17:52,748 INFO MainThread pyrogram.connection.connection Connecting...
2022-08-06 12:17:52,828 INFO MainThread pyrogram.connection.connection Connected! Production DC5 - IPv4 - TCPAbridgedO
2022-08-06 12:17:52,828 INFO MainThread pyrogram.session.session NetworkTask started
2022-08-06 12:17:53,216 INFO MainThread pyrogram.session.session Session initialized: Layer 143
2022-08-06 12:17:53,216 INFO MainThread pyrogram.session.session Device: CPython 3.10.4 - Pyrogram 2.0.35
2022-08-06 12:17:53,216 INFO MainThread pyrogram.session.session System: Linux 5.4.0-1078-oracle (EN)
2022-08-06 12:17:53,216 INFO MainThread pyrogram.session.session Session started
2022-08-06 12:17:53,270 INFO MainThread pyrogram.session.session PingTask started
2022-08-06 12:17:53,539 INFO MainThread pyrogram.dispatcher Started 8 HandlerTasks
2022-08-06 12:17:53,715 INFO MainThread pyrogram.dispatcher Stopped 8 HandlerTasks
2022-08-06 12:17:53,715 INFO MainThread pyrogram.session.session PingTask stopped
2022-08-06 12:17:53,715 INFO MainThread pyrogram.connection.connection Disconnected
2022-08-06 12:17:53,715 INFO MainThread pyrogram.session.session NetworkTask stopped
2022-08-06 12:17:53,715 INFO MainThread pyrogram.session.session Session stopped
2022-08-06 12:17:54,120 INFO MainThread pyrogram.connection.connection Connecting...
2022-08-06 12:17:54,201 INFO MainThread pyrogram.connection.connection Connected! Production DC5 - IPv4 - TCPAbridgedO
2022-08-06 12:17:54,201 INFO MainThread pyrogram.session.session NetworkTask started
2022-08-06 12:17:54,609 INFO MainThread pyrogram.session.session Session initialized: Layer 143
2022-08-06 12:17:54,609 INFO MainThread pyrogram.session.session Device: CPython 3.10.4 - Pyrogram 2.0.35
2022-08-06 12:17:54,609 INFO MainThread pyrogram.session.session System: Linux 5.4.0-1078-oracle (EN)
2022-08-06 12:17:54,609 INFO MainThread pyrogram.session.session Session started
2022-08-06 12:17:54,663 INFO MainThread pyrogram.session.session PingTask started
2022-08-06 12:17:54,841 INFO MainThread pyrogram.dispatcher Started 8 HandlerTasks
2022-08-06 12:17:54,841 INFO MainThread bot pyrogram_session client created
2022-08-06 12:17:55,025 ERROR MainThread root The variable was not found in either the constants or environment, variable is :- UPTOBOX_TOKEN
2022-08-06 12:17:59,486 INFO MainThread telethon.client.uploads Uploading file of 6565 bytes in 1 chunks of 131072
2022-08-06 12:19:30,596 ERROR MainThread pyrogram.dispatcher 'builtin_function_or_method' object has no attribute 'time'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/core/handlers/handle_mirror_cm.py", line 29, in handle_qbit_mirror_command
    await mirror(client, message, isQbit=True)
  File "/usr/src/app/bot/core/handlers/handle_mirror_cm.py", line 114, in mirror
    state, message, path, name = await qbit_dl.add_qb_torrent(link)
  File "/usr/src/app/bot/downloaders/qbit/qbit_downloader.py", line 39, in add_qb_torrent
    time_s= str(time.time()).replace(".","")
AttributeError: 'builtin_function_or_method' object has no attribute 'time'
2022-08-06 12:19:41,182 INFO MainThread telethon.client.uploads Uploading file of 7491 bytes in 1 chunks of 131072`
![image](https://user-images.githubusercontent.com/108970034/183248601-68b8f939-497d-4b1d-9d32-7f54efcf6f2d.png)

**Comment by Sam-Max** [comment]
Yes, I will release a fix tomorrow

**Comment by b1fly** [comment]
> 

thanks bro

**Comment by Sam-Max** [comment]
> > 
> 
> thanks bro

Fixed
