### ISSUE TITLE
tag error

### ISSUE THREAD

**Issue by b1fly** [Sam-Max/Rclone-Tg-Bot#29]
When using /qbmirror to download a magnetic or torrent file, it will not be automatically uploaded to the cloud after the download is complete. I found that it should be the tag problem in the newly added qb configuration file.

`2022-09-02 07:35:13,166 INFO MainThread bot QbitDownload started: 88888axa432554qw864348243 - Hash: 88888axa432554qw864348243
2022-09-02 07:36:58,137 INFO MainThread bot dict_values([<bot.utils.status_utils.qbit_status.qBitTorrentStatus object at 0xfff812243880>])
2022-09-02 07:36:58,137 INFO MainThread bot Cancelling Download: 88888axa432554qw864348243, cause: Download stopped by user!!
2022-09-02 07:37:07,582 INFO MainThread bot QbitDownload started: 88888axa432554qw864348243 - Hash: 88888axa432554qw864348243
2022-09-02 07:38:29,617 ERROR MainThread pyrogram.dispatcher local variable 'tag' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/core/handlers/handle_mirror.py", line 30, in handle_qbit_mirror_command
    await mirror(client, message, isQbit=True)
  File "/usr/src/app/bot/core/handlers/handle_mirror.py", line 140, in mirror
    rclone_mirror = RcloneMirror(path, rmsg, tag)
UnboundLocalError: local variable 'tag' referenced before assignment
2022-09-02 07:39:49,199 INFO MainThread telethon.client.uploads Uploading file of 9263 bytes in 1 chunks of 131072`

![2022-09-02_15-43-39](https://user-images.githubusercontent.com/108970034/188085249-4ee53bcd-ca80-4cb9-b25b-7b08676aa35d.jpg)

**Comment by Sam-Max** [comment]
I will fix today, sorry for the delay

**Comment by bolavefasfas** [comment]
> I will fix today, sorry for the delay

- Bro is the bot using rclone to upload the file to cloud after aira or qbit downloads the file if yes then

- can you adda func that if we download the files from qbit web or aira web then too it should move the files to rclone remote ??

**Comment by Sam-Max** [comment]
> 

Yes, the bot upload to cloud after aira or qbit downloads. The second question don't understand what you mean.

**Comment by b1fly** [comment]
> > 
> 
> Yes, the bot upload to cloud after aria or qbit downloads. The second question don't understand what you mean.

Do you consider increasing video compression function? The TG non -member account will limit the media files below 2GB, so it can compress the video more than 2GB to less than 2GB by compression function and allocate it to achieve the cloud synchronization to TG

https://github.com/WeebTime/Video-Encoder-Bot

**Comment by Sam-Max** [comment]
> > > 
> > 
> > 
> > Yes, the bot upload to cloud after aria or qbit downloads. The second question don't understand what you mean.
> 
> Do you consider increasing video compression function? The TG non -member account will limit the media files below 2GB, so it can compress the video more than 2GB to less than 2GB by compression function and allocate it to achieve the cloud synchronization to TG
> 
> https://github.com/WeebTime/Video-Encoder-Bot

No video compression planned for now
