### ISSUE TITLE
Mega Link Error

### ISSUE THREAD

**Issue by pachax001** [Sam-Max/Rclone-Tg-Bot#31]
I am using a free mega account. When I try to zipmirror or mirror a mega link I get this error.
2022-09-05 02:12:28,128 INFO MainThread telethon.client.uploads Uploading file of 4884 bytes in 1 chunks of 131072
2022-09-05 02:12:29,010 ERROR MainThread pyrogram.dispatcher {'dlinfo': 'failed', 'message': 'no such gid currently exists in downloader'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/modules/mirror.py", line 35, in handle_zip_mirror
    await mirror_leech(client, message, isZip=True)
  File "/usr/src/app/bot/modules/mirror.py", line 151, in mirror_leech
    state, rmsg, path= await mega_dl.execute(path= f'{DOWNLOAD_DIR}{message.id}')
  File "/usr/src/app/bot/downloaders/mega/mega_download.py", line 40, in execute
    status, rmsg, path= await mega_status.create_status()
  File "/usr/src/app/bot/utils/status_utils/mega_status.py", line 31, in create_status
    self._dl_info = await self._obj.loop.run_in_executor(None, partial(self._obj.mega_client.getDownloadInfo, self.__gid))
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/megasdkrestclient/client.py", line 33, in getDownloadInfo
    return checkAndRaise(res, 'dlinfo')
  File "/usr/local/lib/python3.10/dist-packages/megasdkrestclient/utils.py", line 9, in checkAndRaise
    raise MegaSdkRestClientException(obj)
megasdkrestclient.errors.MegaSdkRestClientException: {'dlinfo': 'failed', 'message': 'no such gid currently exists in downloader'}

**Comment by Sam-Max** [comment]
zipmirror is not for mega, only mirror
