### ISSUE TITLE
"Send an Rclone config file" Issue At Supergroup

### ISSUE THREAD

**Issue by GokhanOfficial** [Sam-Max/Rclone-Tg-Bot#35]
Bot is awesome but when I add it to my supergroup, It replies every message with "Send an Rclone config file". Even I send config file. I can't use it on supergroup.

Screenshot: https://prnt.sc/AsHOIbRfXE8g
Note: Bot is admin but saying "This message doesn't contain any downloadable media" to my config file.

Sorry for my bad English.

`2022-09-11 08:40:57,601 ERROR MainThread pyrogram.dispatcher Telegram says: [406 CHANNEL_PRIVATE] - The channel/supergroup is not accessible (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/modules/config.py", line 19, in handle_config
    question= await client.send_message(message.chat.id,
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/send_message.py", line 124, in send_message
    r = await self.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.ChannelPrivate: Telegram says: [406 CHANNEL_PRIVATE] - The channel/supergroup is not accessible (caused by "messages.SendMessage")
2022-09-11 08:40:58,004 INFO MainThread telethon.client.updates Timeout waiting for updates expired
2022-09-11 08:40:58,005 INFO MainThread telethon.client.updates Getting difference for account updates
2022-09-11 08:40:58,047 INFO MainThread telethon.client.updates Getting difference for channel updates
2022-09-11 08:40:58,068 INFO MainThread telethon.client.updates Account is now banned in "I hidden my channel ID" so we can no longer fetch updates from it
2022-09-11 08:43:33,008 INFO MainThread pyrogram.session.session NetworkTask stopped
2022-09-11 08:43:33,009 INFO MainThread pyrogram.session.session PingTask stopped
2022-09-11 08:43:33,009 INFO MainThread pyrogram.connection.connection Disconnected
2022-09-11 08:43:33,010 INFO MainThread pyrogram.session.session Session stopped
2022-09-11 08:43:33,010 INFO MainThread pyrogram.connection.connection Connecting...
2022-09-11 08:43:33,010 INFO MainThread pyrogram.session.session [1] Retrying "messages.DeleteMessages" due to TimeoutError()
2022-09-11 08:43:33,012 INFO MainThread pyrogram.connection.connection Connected! Production DC4 - IPv4 - TCPAbridgedO
2022-09-11 08:43:33,013 INFO MainThread pyrogram.session.session NetworkTask started
2022-09-11 08:43:33,109 INFO MainThread pyrogram.session.session Session initialized: Layer 145
2022-09-11 08:43:33,110 INFO MainThread pyrogram.session.session Device: CPython 3.10.4 - Pyrogram 2.0.51
2022-09-11 08:43:33,110 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1017-oracle (EN)
2022-09-11 08:43:33,110 INFO MainThread pyrogram.session.session Session started
2022-09-11 08:43:33,110 INFO MainThread pyrogram.session.session PingTask started
2022-09-11 08:48:06,795 INFO MainThread telethon.client.updates Timeout waiting for updates expired
2022-09-11 08:48:06,796 INFO MainThread telethon.client.updates Getting difference for account updates
2022-09-11 08:48:21,691 INFO MainThread telethon.client.updates Timeout waiting for updates expired
2022-09-11 08:48:21,691 INFO MainThread telethon.client.updates Getting difference for channel updates
2022-09-11 08:48:25,437 INFO MainThread telethon.client.updates Timeout waiting for updates expired
2022-09-11 08:48:25,437 INFO MainThread telethon.client.updates Getting difference for channel updates
2022-09-11 08:48:41,588 INFO MainThread telethon.client.updates Timeout waiting for updates expired
2022-09-11 08:48:41,588 INFO MainThread telethon.client.updates Getting difference for channel updates
2022-09-11 08:49:19,128 INFO MainThread telethon.client.updates Timeout waiting for updates expired
2022-09-11 08:49:19,129 INFO MainThread telethon.client.updates Getting difference for account updates
2022-09-11 08:49:23,742 INFO MainThread pyrogram.connection.connection Connecting...
2022-09-11 08:49:23,744 INFO MainThread pyrogram.connection.connection Connected! Production DC4 (media) - IPv4 - TCPAbridgedO
2022-09-11 08:49:23,745 INFO MainThread pyrogram.session.session NetworkTask started
2022-09-11 08:49:23,812 INFO MainThread pyrogram.session.session Session initialized: Layer 145
2022-09-11 08:49:23,812 INFO MainThread pyrogram.session.session Device: CPython 3.10.4 - Pyrogram 2.0.51
2022-09-11 08:49:23,812 INFO MainThread pyrogram.session.session System: Linux 5.15.0-1017-oracle (EN)
2022-09-11 08:49:23,812 INFO MainThread pyrogram.session.session Session started
2022-09-11 08:49:23,812 INFO MainThread pyrogram.session.session PingTask started
2022-09-11 08:49:23,827 WARNING MainThread pyrogram.parser.html Unclosed tags: <code> (x1)`

**Comment by CosmosCloudX** [comment]
I have faced same issue rclone config dosent work in grp

**Comment by Sam-Max** [comment]
@GokhanOfficial @CosmosCloudX I am aware of the issue, I will fix when I have some time

**Comment by Sam-Max** [comment]
@GokhanOfficial @CosmosCloudX Giving a second thought I don't think is a good idea to load rclone config from supergroup as other usres will be able to see other people config file.
