### ISSUE TITLE
mirror error

### ISSUE THREAD

**Issue by b1fly** [Sam-Max/Rclone-Tg-Bot#47]
/mirror download torrent stuck at 99.97%.
/mirror After calling aria2 to download the file and uploading it to the cloud, the aria2 file will also be uploaded.
![image](https://user-images.githubusercontent.com/108970034/193811878-db144be1-7120-4e99-9c61-771c8936ec78.png)
![image](https://user-images.githubusercontent.com/108970034/193811909-f9cb9483-cee8-4a73-b539-65b6cd9e58df.png)

**Comment by b1fly** [comment]
```
2022-10-04 11:26:23,757 INFO MainThread bot QbitDownload started: 224c2ee3621c82723fdeed25fcdb932b3bcc75d3 - Hash: 224c2ee3621c82723fdeed25fcdb932b3bcc75d3
2022-10-04 11:30:53,258 INFO MainThread bot type object 'MirrorStatus' has no attribute 'STATUS_SEEDING'
2022-10-04 11:38:12,278 ERROR MainThread pyrogram.dispatcher 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/modules/mirror.py", line 30, in handle_mirror
    await mirror_leech(client, message)
  File "/usr/src/app/bot/modules/mirror.py", line 190, in mirror_leech
    await ml.execute()
  File "/usr/src/app/bot/helper/mirror_leech_utils/mirror_leech.py", line 125, in execute
    await rc_mirror.mirror()
  File "/usr/src/app/bot/helper/mirror_leech_utils/download_utils/rclone/rclone_mirror.py", line 43, in mirror
    status= await rclone_status.start()
  File "/usr/src/app/bot/helper/mirror_leech_utils/status_utils/rclone_status.py", line 69, in start
    self._rc_process.kill()
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 143, in kill
    self._transport.kill()
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 153, in kill
    self._check_proc()
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 142, in _check_proc
    raise ProcessLookupError()
ProcessLookupError
2022-10-04 11:39:12,373 INFO MainThread bot Removing Download
```

**Comment by Sam-Max** [comment]
@b1fly It is not torrent stuck is only status message not deleting
